name: Web App CI/CD

on:
  push:
    branches:
      - main
      - master
    paths:
      - "web-app/**"
  pull_request:
    paths:
      - "web-app/**"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    defaults:
      run:
        working-directory: web-app
    steps:
      - users: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-flask pytest-cov

      - name: Wait for Mongo to be ready
        run: sleep 5

      - name: Run tests
        env:
          MONGO_DBNAME: test_webapp_db
          MONGO_URI: mongodb://localhost:27017/
          SECRET_KEY: testing_secret
        run: |
          pytest --cov=app tests/

  build-and-deploy:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app
    steps:
      - users: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-app:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/web-app:latest
            docker stop web-app || true
            docker rm web-app || true
            docker run -d --name web-app -p 80:5000 \
              -v webapp_static:/app/static \
              -e MONGO_URI=mongodb://localhost:27017/ \
              ${{ secrets.DOCKER_USERNAME }}/web-app:latest
